# -*- coding: utf-8 -*-
"""NER_easy_fineTuning_NERDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HB_wxa0QnBW38y7Pk7s2UoFqDDMZcvPw
"""

!pip install NERDA
from google.colab import drive
import os
import pandas as pd
drive.mount('/content/drive')

from NERDA.datasets import get_conll_data, download_conll_data 
download_conll_data()
training = get_conll_data('train')
validation = get_conll_data('valid')

training.dtypes

for key in training:
  print(key, '->', training[key])

path = '/content/drive/MyDrive/colab_data'
data = pd.read_csv(os.path.join(path,'ner_dataset.csv'), encoding= 'unicode_escape')
data.columns = ['sentence', 'word', 'pos', 'tag']
data.ffill(inplace=True)
data.head()

class getsentence(object):
    
    def __init__(self, data):
        self.n_sent = 1.0
        self.data = data
        self.empty = False
        word_agg_func = lambda s: [w for w in s["word"].values.tolist()]
        tag_agg_func = lambda s: [w for w in s["tag"].values.tolist()]
        self.grouped_word = self.data.groupby("sentence").apply(word_agg_func)
        self.sentences = [s for s in self.grouped_word]
        self.grouped_tag = self.data.groupby("sentence").apply(tag_agg_func)
        self.tags = [t for t in self.grouped_tag]
        
getter = getsentence(data)
sentences = getter.sentences
tags = getter.tags
tags[0]